version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres

  identity-api:
    image: quay.io/keycloak/keycloak:26.1
    container_name: identity.api
    depends_on:
      - postgres

  tasks-api:
    image: tasks-flow/tasks.api:linux-1.0
    build:
      context: .
      dockerfile: Tasks/Tasks.API/Dockerfile
    container_name: tasks.api
    depends_on:
      - postgres
      - identity-api