version: '3.8'

services:
  postgres:
    volumes:
      - ../tools/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432

  identity-api:
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=123
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=123
    ports:
      - 5001:8080
    command: [ "start-dev" ]

  tasks-api:
    environment:
      - ConnectionStrings__TasksDB=Host=postgres;Port=5432;Database=Tasks;Username=admin;Password=123
      - OpenApi__Auth__Authority=http://localhost:5001/realms/task-flow-realm
      - OpenApi__Auth__ClientSecret=qgdcKO2LJ8knahIMY8vlnciMjWFvkbhj
      - Identity__Authority=http://identity-api:8080/realms/task-flow-realm
      - Identity__ValidIssuers__0=http://localhost:5001/realms/task-flow-realm
    ports:
      - 5002:8080
    