name: Dev Pipeline

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  prepare:
    name: Prepare Environment 
    uses: ./.github/actions/prepare/action.yml

  build:
    name: Build Tasks.API
    needs: prepare
    uses: ./.github/actions/build/action.yml
    with:
      project-dir: src/Tasks/Tasks.API

  unit-tests:
    name: Run Unit Tests
    needs: build
    uses: ./.github/actions/test/action.yml
    with:
      test-project-dir: src/Tasks/Tasks.UnitTests
