# name: Dev Pipeline

# on:
#   push:
#     branches: [dev]

#   pull_request:
#     branches: [dev]

# env:
#   PROJECT_DIR: src/Tasks/Tasks.API
#   UNIT_TESTS_DIR: src/Tasks/Tasks.UnitTests
#   DOTNET_VERSION: 9.0.x

# jobs:
#   build:
#     name: Build Project
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

#       - name: Restore Project
#         working-directory: ${{ env.PROJECT_DIR }}
#         run: dotnet restore

#       - name: Build Project
#         working-directory: ${{ env.PROJECT_DIR }}
#         run: dotnet build --configuration Release --no-restore

#   unit-tests:
#     name: Run Unit Tests
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

#       - name: Restore Project
#         working-directory: ${{ env.UNIT_TESTS_DIR }}
#         run: dotnet restore

#       - name: Build Project
#         working-directory: ${{ env.UNIT_TESTS_DIR }}
#         run: dotnet build --no-restore

#       - name: Run Unit Tests
#         working-directory: ${{ env.UNIT_TESTS_DIR }}
#         run: dotnet test --no-build --no-restore
