name: Dev Pipeline

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare Enviroment
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare

  build:
    runs-on: ubuntu-latest
    name: Build .NET project
    needs: prepare
    steps:
      - uses: ./.github/actions/build
    

  # prepare:
  #   name: Prepare Environment 
  #   uses: ./github/workflows/action.yml

  # build:
  #   name: Build Tasks.API
  #   needs: prepare
  #   uses: ./.github/workflows/actions/build/action.yml
  #   with:
  #     project-dir: src/Tasks/Tasks.API

  # unit-tests:
  #   name: Run Unit Tests
  #   needs: build
  #   uses: ./.github/workflows/actions/test/action.yml
  #   with:
  #     test-project-dir: src/Tasks/Tasks.UnitTests
