name: Main Pipeline

on:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "9.0.x"

jobs:

  build:
    uses: ./.github/workflows/templates/build.yml
    with:
      project-dir: src/Tasks/Tasks.API

  unit-tests:
    uses: ./.github/workflows/templates/unit-tests.yml
    needs: build
    with:
      unit-tests-dir: src/Tasks/Tasks.UnitTests

  deploy:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      