name: Unit Tests Template

on:
  workflow_call:
    inputs:
      unit-tests-dir:
        type: string
        required: true

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Unit Tests
        working-directory: ${{ inputs.unit-tests-dir }}
        run: dotnet test --configuration Release
